services:
  api:
    build:
      context: .
      target: production

    container_name: pokemon-api

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production

    restart: unless-stopped