apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true # Loki como origen por defecto para buscar logs fácilmente
    version: 1
    editable: false
    apiVersion: 1
    uid: loki
    jsonData:
      derivedFields:
        # Esto permite que desde los logs en Loki (donde veas un "trace_id")
        # Grafana genere un link directo que abra ese trace en Tempo.
        - datasourceUid: tempo
          matcherRegex: '"trace_id":"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'
