{
 "title": "Pokemon API Observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Infraestructura",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers up",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "up", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Errores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request errores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(http_requests_total{status_code=~\"5..\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event loop lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Garbage Collector",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(nodejs_gc_duration_seconds_sum[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime proceso",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Estado general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node.js Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}