receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 100
    timeout: 1s

exporters:
  # Exportar trazas a Tempo
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Exportar logs a Loki (Útil si la app los envia vía OTLP, aunque también pueden ir directo)
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # Exporter por consola útil para debug
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
